server:
  port: 53020

spring:
  application:
    name: uaa-service
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'

app:
  id: uaa-service
apollo:
  meta: http://192.168.158.162:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,micro_service.spring-boot-druid,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-cloud-feign,micro_service.spring-ribbon,micro_service.spring-boot-redis,micro_service.spring-freemarker

logging:
  config: classpath:log4j2-dev.xml
